### ISSUE TITLE
textAlign

### ISSUE THREAD

**Issue by romenhub** [cagpie/node-canvas-with-twemoji#1]
if textAlign set to 'center' result will like this
problem in emoji
https://media.discordapp.net/attachments/673388483322183713/691823726165229588/Devs-Goodbye.png?width=908&height=436

**Comment by cagpie** [comment]
Thank you for the reporting!

I cannot implement it yet. and Not likely to do for a while.
I'll do it when I have time. sorry😢

**Comment by cagpie** [comment]
This issue has fixed at https://github.com/cagpie/node-canvas-with-twemoji/commit/5383ffec3bdcc961cbd0579e29572881b32af1c5

and I have published to npm as version 0.1.2
https://www.npmjs.com/package/node-canvas-with-twemoji

@AnosVoldigoad

**Comment by namekinggamerboy** [comment]
![not fix](https://cdn.discordapp.com/attachments/675640023273701437/758339138193457192/welcome.png)

This issue not fix new update
